version: '3'

services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: sc2_stats
        MYSQL_USER: admin
        MYSQL_PASSWORD: ABcd1234
        MYSQL_ROOT_PASSWORD: docker
      ports:
        - '3306:3306'
      networks:
        - default
      volumes:
        - ./logs/mysql:/var/log/mysql
        - ./mysql:/var/lib/mysql
    sc2:
      build: .
      ports:
        - '4620:80'
      restart: always
      networks:
        - default
      volumes:
        - ./sc2ai:/sc2ai
        - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        - ./cron/crontab:/etc/crontab
      depends_on:
        - mysql
networks:
    default:
